DROP DATABASE IF EXISTS `login`;
CREATE DATABASE IF NOT EXISTS `login`;
USE `login`;
DROP TABLE IF EXISTS `Login`;
CREATE TABLE `Login`.`PageCache` (
`ID` INT NOT NULL ,
`HTML` TEXT NOT NULL ,
`GenTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY  (`ID`)
) ENGINE = MYISAM ;
